import { DrawingElement } from '../store/useStore';
import { jsPDF } from 'jspdf';

export const exportToPDF = (elements: DrawingElement[], spoolName: string) => {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  });

  doc.setFontSize(18);
  doc.text(`Spool Drawing: ${spoolName}`, 10, 15);
  doc.setFontSize(10);
  doc.text(`Generated by SpoolPro Mobile - ${new Date().toLocaleDateString()}`, 10, 22);

  // Simple drawing reproduction on PDF
  const scale = 0.5; // mm per pixel roughly
  const offsetX = 10;
  const offsetY = 30;

  elements.forEach(el => {
    if (el.type === 'pipe' && el.points) {
      doc.setLineWidth(1);
      doc.setDrawColor(0, 100, 255);
      doc.line(
        offsetX + el.points[0] * scale,
        offsetY + el.points[1] * scale,
        offsetX + el.points[2] * scale,
        offsetY + el.points[3] * scale
      );
      if (el.label) {
        doc.setFontSize(6);
        doc.text(el.label, offsetX + (el.points[0] + el.points[2]) / 2 * scale, offsetY + (el.points[1] + el.points[3]) / 2 * scale);
      }
    } else if (el.type === 'accessory' && el.position) {
      doc.setDrawColor(255, 100, 0);
      doc.circle(offsetX + el.position.x * scale, offsetY + el.position.y * scale, 2, 'S');
      doc.setFontSize(5);
      doc.text(el.accessoryType || 'ACC', offsetX + el.position.x * scale + 2, offsetY + el.position.y * scale);
    }
  });

  doc.save(`${spoolName}.pdf`);
};

export const exportToDXF = (elements: DrawingElement[], spoolName: string) => {
  let dxf = `0\nSECTION\n2\nHEADER\n0\nENDSEC\n`;
  dxf += `0\nSECTION\n2\nTABLES\n0\nENDSEC\n`;
  dxf += `0\nSECTION\n2\nBLOCKS\n0\nENDSEC\n`;
  dxf += `0\nSECTION\n2\nENTITIES\n`;

  elements.forEach(el => {
    if (el.type === 'pipe' && el.points) {
      dxf += `0\nLINE\n8\nPIPES\n`;
      dxf += `10\n${el.points[0]}\n20\n${-el.points[1]}\n30\n0.0\n`; // y is inverted in CAD
      dxf += `11\n${el.points[2]}\n21\n${-el.points[3]}\n31\n0.0\n`;
    } else if (el.type === 'accessory' && el.position) {
      dxf += `0\nCIRCLE\n8\nFITTINGS\n`;
      dxf += `10\n${el.position.x}\n20\n${-el.position.y}\n30\n0.0\n40\n10.0\n`;
    }
  });

  dxf += `0\nENDSEC\n0\nEOF\n`;

  const blob = new Blob([dxf], { type: 'application/dxf' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${spoolName}.dxf`;
  link.click();
};
